source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '9.0'

target 'RocketTestSwift' do
  #pod 'RocketKit', :podspec => 'https://github.com/nickbolton/RocketKit.git/RocketKit.podspec'
  pod 'RocketKit', :path => '~/src/pixelbleed/RocketKit'
end

#post_install do |installer_representation|
#  installer_representation.project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings['CODE_SIGN_IDENTITY'] = 'iPhone Developer'
#    end
#  end
#end
